### ISSUE TITLE
it would be more intuitive if there was a comment whats being rendered here (read comments)

### ISSUE THREAD

**Issue by BekaBadzagua** [Leonssizm/simple_blogpost_website#4]
https://github.com/Leonssizm/simple_blogpost_website/blob/f34060703c433ebe0faf25529524f5b848492fb6/posts-page.html#L21

**Comment by BekaBadzagua** [comment]
```javascript
<div id="card-body" class=" w-50 p-1 m-auto">
    <!-- posts  -->
</div>
```

**Comment by Leonssizm** [comment]
https://github.com/Leonssizm/simple_blogpost_website/commit/6fd1ae3e4598a0ba2127a4ffa1bac23cdc7cfff7
